name: Build project and deploy to myASP.NET
on: [push]

jobs:
  build_and_deploy:
    name: Build package and deploy to myASP.NET
    runs-on: windows-latest
    steps:
      - name: build file
        uses: actions/checkout@v1

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win6057.site4now.net
          username: brnznetfilter
          password: 33A511be@brnznetfilter
